//
//  AppText.swift
//  ruri
//

import SwiftUI

enum AppText {
    static let errorTitle: LocalizedStringKey = "Error"
    static let okButton: LocalizedStringKey = "OK"
    static let githubLoginAlertTitle: LocalizedStringKey = "GitHub Login"
    static let externalPullRequestWorktreeAlertTitle: LocalizedStringKey = "Create Pull Request Worktree?"
    static let aboutCommand: LocalizedStringKey = "About Ruri"
    static let openFolderCommand: LocalizedStringKey = "Open Folder..."
    static let closeTabCommand: LocalizedStringKey = "Close Tab"
    static let saveCommand: LocalizedStringKey = "Save"
    static let saveConflictAlertTitle: LocalizedStringKey = "Overwrite External Changes?"
    static let saveConflictAlertMessage: LocalizedStringKey = "Saving will overwrite the version currently on disk."
    static let overwriteButton: LocalizedStringKey = "Overwrite"
    static let renameCommand: LocalizedStringKey = "Rename"
    static let copyPathCommand: LocalizedStringKey = "Copy Path"
    static let copyRelativePathCommand: LocalizedStringKey = "Copy Relative Path"
    static let showChangedFilesOnlyInTreeCommand: LocalizedStringKey = "Show Changed Files Only"
    static let focusCurrentFileInTreeCommand: LocalizedStringKey = "Reveal Current File in Tree"
    static let newWorktreeCommand: LocalizedStringKey = "New Worktree..."
    static let newWorktreeTitle: LocalizedStringKey = "New Worktree"
    static let newWorktreeLocalSource: LocalizedStringKey = "Local"
    static let newWorktreeRemoteSource: LocalizedStringKey = "Remote"
    static let newWorktreeBranchPlaceholder: LocalizedStringKey = "Branch name"
    static let newWorktreeRemoteSearchPlaceholder: LocalizedStringKey = "Search remote branches"
    static let newWorktreeFetchingRemoteBranches: LocalizedStringKey = "Fetching remote branches..."
    static let newWorktreeNoRemoteBranches: LocalizedStringKey = "No remote branches"
    static let newWorktreeNoRemoteBranchMatches: LocalizedStringKey = "No matching remote branches"
    static let worktreeInitializationCommandPlaceholder: LocalizedStringKey = "Initialization command"
    static let retryInitializationButton: LocalizedStringKey = "Retry Initialization"
    static let deleteWorktreeCommand: LocalizedStringKey = "Delete Worktree..."
    static let pullWorktreeCommand: LocalizedStringKey = "Pull Worktree"
    static let deleteWorktreeAlertTitle: LocalizedStringKey = "Delete Worktree?"
    static let deleteWorktreeAlertMessage: LocalizedStringKey = "The worktree directory and local branch will be removed."
    static let createButton: LocalizedStringKey = "Create"
    static let deleteButton: LocalizedStringKey = "Delete"
    static let retryButton: LocalizedStringKey = "Retry"
    static let noFileSelectedTitle: LocalizedStringKey = "No File Selected"
    static let selectFileDescription: LocalizedStringKey = "左のファイルツリーからファイルを選択してください"
    static let noFolderOpenedTitle: LocalizedStringKey = "No Folder Opened"
    static let openFolderDescription: LocalizedStringKey = "Open Folderからプロジェクトフォルダを選択してください"
    static let loading: LocalizedStringKey = "Loading"
    static let fileSearchPlaceholder: LocalizedStringKey = "Search files by name"
    static let fileSearchIndexing: LocalizedStringKey = "Indexing..."
    static let fileSearchNoResults: LocalizedStringKey = "No matching files"
    static let findCommand: LocalizedStringKey = "Find"
    static let findAndReplaceCommand: LocalizedStringKey = "Find and Replace"
    static let findInFilesCommand: LocalizedStringKey = "Find in Files"
    static let goToImplementationCommand: LocalizedStringKey = "Go to Symbol or Usages"
    static let editorCommandMenu: LocalizedStringKey = "Editor"
    static let lineWrapCommand: LocalizedStringKey = "Line Wrap"
    static let navigationCommandMenu: LocalizedStringKey = "Navigate"
    static let navigateBackCommand: LocalizedStringKey = "Back"
    static let navigateForwardCommand: LocalizedStringKey = "Forward"
    static let textSearchPlaceholder: LocalizedStringKey = "Search text"
    static let textSearchDirectoryPlaceholder: LocalizedStringKey = "Directory"
    static let textSearchFileMaskPlaceholder: LocalizedStringKey = "File mask"
    static let textSearchRegexToggle: LocalizedStringKey = "Regex"
    static let textSearchCaseSensitiveToggle: LocalizedStringKey = "Case"
    static let textSearchSearching: LocalizedStringKey = "Searching..."
    static let textSearchNoResults: LocalizedStringKey = "No matches"
    static let codeUsageTitle: LocalizedStringKey = "Usages"
    static let codeUsageNoResults: LocalizedStringKey = "No usages"
    static let searchCommandMenu: LocalizedStringKey = "Search"
    static let tabReturnedTitle: LocalizedStringKey = "Tab Returned"
    static let tabReturnedDescription: LocalizedStringKey = "このタブはメインウィンドウに戻りました"
    static let terminalCommandMenu: LocalizedStringKey = "Terminal"
    static let runCommandMenu: LocalizedStringKey = "Run"
    static let runCommand: LocalizedStringKey = "Run"
    static let stopCommand: LocalizedStringKey = "Stop"
    static let runConfigurationsCommand: LocalizedStringKey = "Run Configurations..."
    static let runConfigurationsTitle: LocalizedStringKey = "Run Configurations"
    static let addRunConfigurationButton: LocalizedStringKey = "Add"
    static let runConfigurationNamePlaceholder: LocalizedStringKey = "Name"
    static let runConfigurationCommandPlaceholder: LocalizedStringKey = "Shell command"
    static let doneButton: LocalizedStringKey = "Done"
    static let toggleTerminalCommand: LocalizedStringKey = "Toggle Terminal"
    static let newTerminalTabCommand: LocalizedStringKey = "New Terminal Tab"
    static let worktreeOverviewTitle: LocalizedStringKey = "Worktree"
    static let toggleTerminalOverviewCommand: LocalizedStringKey = "Toggle Worktree"
    static let refreshWorktreesCommand: LocalizedStringKey = "Refresh Worktree"
    static let noWorktreesTitle: LocalizedStringKey = "No Worktree"
    static let noWorktreesDescription: LocalizedStringKey = "Open a folder to view worktrees."
    static let worktreeMemoPlaceholder: LocalizedStringKey = "Work memo"
    static let terminalCloseAlertTitle: LocalizedStringKey = "Close Terminal Tab?"
    static let terminalCloseAlertMessage: LocalizedStringKey = "This terminal still has a running process."
    static let terminateButton: LocalizedStringKey = "Terminate"
    static let cancelButton: LocalizedStringKey = "Cancel"
}
